name: tvOS
targets:
  tvOS:
    type: application
    platform: tvOS
    deploymentTarget: "14.0"
    sources: [My App]
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.AppInstalleriOS.Test-App
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
